### ISSUE TITLE
кнопка иногда появляется, а иногда нет

### ISSUE THREAD

**Issue by prtolem** [ilyhalight/lzt-upgrade#3]
я так понял что кнопка для открытия меню находится под в выпадающем меню т.е. здесь
![image](https://user-images.githubusercontent.com/66413287/205671019-1fdd8f0c-68d3-428c-96db-d6c05a204bd2.png)
но у меня она чаще всего не отображается, а если и отображается, то при нажатии ничего не происходит

**Comment by ilyhalight** [comment]
Можешь подсказать какой браузер и версию lzt upgrade используешь? Просто, у меня нет такой проблемы на последней версии, и если в консоли браузера что-то пишет красным текстом, то это, тоже, могло бы помочь разобраться с этой проблемкой.
![изображение](https://user-images.githubusercontent.com/62353659/205734751-cd2bb3db-eed5-45af-a982-00f199bdeb0b.png)
